name: Rust CI

on:
  push:
    branches: [Current]
  pull_request:
    branches: [Current]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy

      - name: Run tests
        run: cargo test

      - name: Run clippy
        run: cargo clippy -- -D warnings
